name: Azure Storage Static Website Deployment

on:
  push:
    branches:
      - main  # You can adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install azcopy
      run: |
        curl -Lo azcopy_linux_amd64_10.10.0.tar.gz https://aka.ms/downloadazcopy-v10-linux
        tar -xf azcopy_linux_amd64_10.10.0.tar.gz
        sudo cp ./azcopy_linux_amd64_10.10.0/azcopy /usr/bin/
        azcopy --version
      shell: bash

    - name: Upload files to Azure Storage
      run: |
        export AZCOPY_SOURCE="./frontend"
        export AZCOPY_DEST="https://cneleesbarelinkwebsite.blob.core.windows.net/\$web/"
        
        azcopy copy "$AZCOPY_SOURCE" "$AZCOPY_DEST?$AZCOPY_SAS_TOKEN" --recursive=true
      env:
        AZCOPY_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}

