name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and prepare your webpages
      run: |
        # Your build and webpage preparation steps here

    - name: Deploy to Azure Blob Storage
      run: |
        az storage blob upload-batch --destination $WEB_ROOT_CONTAINER_NAME --source ./frontend --sas $AZURE_BLOB_SAS_URL --pattern '*'

env:
  WEB_ROOT_CONTAINER_NAME: $web
  AZURE_BLOB_SAS_URL: ${{ secrets.AZURE_BLOB_SAS_URL }}
